import ./algorithm/test_aesgcm
import ./algorithm/test_aesgcmsiv
import ./algorithm/test_argon2
import ./algorithm/test_bcrypt
import ./algorithm/test_blake2
import ./algorithm/test_chacha20poly1305
import ./algorithm/test_ed25519
import ./algorithm/test_hkdf
import ./algorithm/test_hmac
import ./algorithm/test_p256
import ./algorithm/test_bls
import ./algorithm/test_p384
import ./algorithm/test_passwordhash
import ./algorithm/test_pbkdf2
import ./algorithm/test_pem
import ./algorithm/test_pkcs8
import ./algorithm/test_rsa
import ./algorithm/test_schnorr
import ./algorithm/test_scrypt
import ./algorithm/test_secp256k1
import ./algorithm/test_secp256k1_ecdsa_der
import ./algorithm/test_sha256
import ./algorithm/test_sha3
import ./algorithm/test_x509
