use core::ffi::c_int;

mod aead_common;
mod aes_gcm;
mod aes_gcm_siv;
mod argon2;
#[cfg(not(target_arch = "wasm32"))]
mod bcrypt;
#[cfg(target_arch = "wasm32")]
mod bcrypt_wasm;
mod blake2;
mod chacha20poly1305;
mod ed25519;
mod hash;
mod hkdf;
mod hmac;
mod oid;
mod p256;
mod p384;
mod password_hash;
mod pbkdf2;
mod rsa;
mod schnorr;
mod scrypt;
mod secp256k1;
mod x509;

#[cfg(target_arch = "wasm32")]
#[allow(unused_imports)]
pub(crate) use bcrypt_wasm as bcrypt;

pub const RUSTCRYPTO_OK: c_int = 0;
pub const RUSTCRYPTO_ERR_NULL_OUTPUT: c_int = 1;
pub const RUSTCRYPTO_ERR_OUTPUT_TOO_SHORT: c_int = 2;
pub const RUSTCRYPTO_ERR_NULL_INPUT_WITH_DATA: c_int = 3;
pub const RUSTCRYPTO_ERR_INVALID_SECRET_KEY: c_int = 4;
pub const RUSTCRYPTO_ERR_INVALID_PUBLIC_KEY_FORMAT: c_int = 5;
pub const RUSTCRYPTO_ERR_INVALID_MESSAGE_DIGEST: c_int = 6;
pub const RUSTCRYPTO_ERR_INVALID_SIGNATURE: c_int = 7;
pub const RUSTCRYPTO_ERR_VERIFICATION_FAILED: c_int = 8;
pub const RUSTCRYPTO_ERR_INVALID_LENGTH: c_int = 9;
pub const RUSTCRYPTO_ERR_INVALID_PRK_LENGTH: c_int = 10;
pub const RUSTCRYPTO_ERR_AUTHENTICATION_FAILED: c_int = 11;
pub const RUSTCRYPTO_ERR_INVALID_KEY_LENGTH: c_int = 12;
pub const RUSTCRYPTO_ERR_INVALID_NONCE_LENGTH: c_int = 13;
pub const RUSTCRYPTO_ERR_INVALID_TAG_LENGTH: c_int = 14;
pub const RUSTCRYPTO_ERR_INVALID_PARAMETER: c_int = 15;
pub const RUSTCRYPTO_ERR_INVALID_PASSWORD_HASH_FORMAT: c_int = 16;
pub const RUSTCRYPTO_ERR_INVALID_CERTIFICATE: c_int = 17;
pub const RUSTCRYPTO_ERR_DECRYPTION_FAILED: c_int = 18;
pub const RUSTCRYPTO_ERR_RANDOM_FAILED: c_int = 19;
pub const RUSTCRYPTO_ERR_PANIC: c_int = -1;

pub const SHA256_DIGEST_LEN: usize = 32;
pub const HMAC_SHA256_MAC_LEN: usize = 32;
pub const HKDF_SHA256_PRK_LEN: usize = SHA256_DIGEST_LEN;
pub const HKDF_SHA256_MAX_OKM_LEN: usize = SHA256_DIGEST_LEN * 255;
pub const CHACHA20POLY1305_KEY_LEN: usize = 32;
pub const CHACHA20POLY1305_NONCE_LEN: usize = 12;
pub const CHACHA20POLY1305_TAG_LEN: usize = 16;
pub const AES256GCM_KEY_LEN: usize = 32;
pub const AES256GCM_NONCE_LEN: usize = 12;
pub const AES256GCM_TAG_LEN: usize = 16;
pub const AES256GCMSIV_KEY_LEN: usize = 32;
pub const AES256GCMSIV_NONCE_LEN: usize = 12;
pub const AES256GCMSIV_TAG_LEN: usize = 16;
pub const BLAKE2B_512_DIGEST_LEN: usize = 64;
pub const BLAKE2S_256_DIGEST_LEN: usize = 32;
pub const SHA3_256_DIGEST_LEN: usize = 32;
pub const KECCAK_256_DIGEST_LEN: usize = 32;
pub const SECP256K1_SECRET_KEY_LEN: usize = 32;
pub const SECP256K1_PUBLIC_KEY_COMPRESSED_LEN: usize = 33;
pub const SECP256K1_PUBLIC_KEY_UNCOMPRESSED_LEN: usize = 65;
pub const SECP256K1_SIGNATURE_LEN: usize = 64;
pub const SECP256K1_SIGNATURE_DER_MAX_LEN: usize = 72;
pub const SECP256K1_MESSAGE_DIGEST_LEN: usize = 32;
pub const SECP256K1_SCHNORR_PUBLIC_KEY_LEN: usize = 32;
pub const SECP256K1_SCHNORR_SIGNATURE_LEN: usize = 64;
pub const P256_SECRET_KEY_LEN: usize = 32;
pub const P256_PUBLIC_KEY_COMPRESSED_LEN: usize = 33;
pub const P256_PUBLIC_KEY_UNCOMPRESSED_LEN: usize = 65;
pub const P256_SIGNATURE_LEN: usize = 64;
pub const P256_MESSAGE_DIGEST_LEN: usize = 32;
pub const P256_PRIVATE_KEY_DER_MAX_LEN: usize = 256;
pub const P256_PUBLIC_KEY_DER_MAX_LEN: usize = 128;
pub const P256_PRIVATE_KEY_PEM_MAX_LEN: usize = 512;
pub const P256_PUBLIC_KEY_PEM_MAX_LEN: usize = 256;
pub const P384_SECRET_KEY_LEN: usize = 48;
pub const P384_PUBLIC_KEY_COMPRESSED_LEN: usize = 49;
pub const P384_PUBLIC_KEY_UNCOMPRESSED_LEN: usize = 97;
pub const P384_SIGNATURE_LEN: usize = 96;
pub const P384_MESSAGE_DIGEST_LEN: usize = 48;
pub const P384_PRIVATE_KEY_DER_MAX_LEN: usize = 256;
pub const P384_PUBLIC_KEY_DER_MAX_LEN: usize = 160;
pub const P384_PRIVATE_KEY_PEM_MAX_LEN: usize = 512;
pub const P384_PUBLIC_KEY_PEM_MAX_LEN: usize = 320;
pub const X509_CERT_DER_MAX_LEN: usize = 8192;
pub const X509_CERT_PEM_MAX_LEN: usize = 11000;
pub const RSA_PRIVATE_KEY_DER_MAX_LEN: usize = 4096;
pub const RSA_PUBLIC_KEY_DER_MAX_LEN: usize = 2048;
pub const RSA_SIGNATURE_LEN_MIN: usize = 1;
pub const RSA_SIGNATURE_DER_MAX_LEN: usize = 4096;
pub const RSA_OAEP_MAX_PLAINTEXT_LEN: usize = 4096;
pub const RSA_OAEP_MAX_CIPHERTEXT_LEN: usize = 4096;
pub const RSA_PKCS1V15_MAX_PLAINTEXT_LEN: usize = 4096;
pub const RSA_PKCS1V15_MAX_CIPHERTEXT_LEN: usize = 4096;
pub const ED25519_PRIVATE_KEY_LEN: usize = 32;
pub const ED25519_PUBLIC_KEY_LEN: usize = 32;
pub const ED25519_SIGNATURE_LEN: usize = 64;
pub const ED25519_PRIVATE_KEY_DER_MAX_LEN: usize = 48;
pub const ED25519_PUBLIC_KEY_DER_MAX_LEN: usize = 44;
pub const ED25519_PRIVATE_KEY_PEM_MAX_LEN: usize = 119;
pub const ED25519_PUBLIC_KEY_PEM_MAX_LEN: usize = 113;
pub const ARGON2ID_MIN_HASH_LEN: usize = 4;
pub const ARGON2ID_MAX_HASH_LEN: usize = u32::MAX as usize;
pub const BCRYPT_HASH_LEN: usize = 60;
pub const BCRYPT_MIN_COST: u32 = 4;
pub const BCRYPT_MAX_COST: u32 = 31;
pub const BCRYPT_DEFAULT_COST: u32 = 12;
pub const BCRYPT_MAX_PASSWORD_LEN: usize = 71;
